atlas/atlas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('files.urls', 'files'), namespace='files')),

    path('users/', include(('users.urls', 'users'), namespace='users')),
]

atlas/files/urls.py
from django.urls import path
from files import views

urlpatterns = [

    path(
        route='',
        view=views.index,
        name='feed'
    ),

]

atlas/users/urls.py
from django.urls import path
from users import views

urlpatterns = [

    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/', 
        view=views.LogoutView.as_view(), 
        name='logout'
        ),

    path(
        route='signup/', 
        view=views.SignUpView.as_view(), 
        name='signup'
        ),

]

atlas/files/models.py
from django.db import models

# Create your models here.

class File_Header(models.Model):
    """
    File_Header part
    """

    tipo_documento = models.CharField(max_length=2, null=False)
    numero_documento = models.IntegerField(null=False)
    razon_social = models.CharField(max_length=100, null=False)
    referencia = models.IntegerField(null=False)
    solicitud = models.CharField(max_length=100, null=False)
    
    def __str__(self):
        return self.tipo_documento + '-' + str(self.numero_documento)

class File_Fixed(models.Model):
    '''
    File Fixed part
    '''
    tipo_documento = models.CharField(max_length=2, null=False)
    numero_documento = models.IntegerField(null=False)
    nombre_cotizante = models.CharField(max_length=100, null=True)
    cargo = models.CharField(max_length=100, null=True)
    anio = models.IntegerField(null=False)
    mes = models.IntegerField(null=False)
    salario = models.IntegerField(null=True)
    dias_trab = models.IntegerField(null=True)
    dias_incap = models.IntegerField(null=True)
    dias_licen = models.IntegerField(null=True)
    total_dias = models.IntegerField(null=True)
    f_ingreso = models.DateField(null=True)
    #add a foreign key to the file header table referencia field
    referencia = models.OneToOneField(File_Header, on_delete=models.CASCADE)

atlas/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    """User profile model"""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return a string representation of the model"""
        return self.user.username

atlas/users/forms.py
# User forms

# Django

from django import forms  # Import forms

#Models
from django.contrib.auth.models import User

from users.models import UserProfile


class SignUpForm(forms.Form):
    """Sign up form"""
    username = forms.CharField(min_length=4, max_length=50)
    password = forms.CharField(max_length=70, widget=forms.PasswordInput())
    password_confirmation = forms.CharField(
        max_length=70, widget=forms.PasswordInput())
    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)
    email = forms.CharField(min_length=6, max_length=70,
                            widget=forms.EmailInput())
    
    def clean_username(self):
        """Username must be unique"""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        """Verify password confirmation matchs"""
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')
        return data

    def save(self):
        """Create user and profile"""
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = UserProfile(user=user)
        profile.save()

atlas/files/views.py
from django.shortcuts import render

# Create your views here.

import pandas as pd
from files.models import File_Header, File_Fixed
from sqlalchemy import create_engine
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    if request.method == 'GET':
        return render(request, 'file.html')
    else:
        excel_file = request.FILES['excel_file']

        file_header = pd.read_excel(
            excel_file, 
            sheet_name='NÓMINA', 
            skiprows=2, 
            nrows=1, 
            usecols='B:D,I:J')

        file_header = file_header.rename(
            columns={
                'TIPO DOCUMENTO APORTANTE': 'tipo_documento',
                'NUMERO DOCUMENTO APORTANTE': 'numero_documento', 
                'RAZON SOCIAL': 'razon_social', 
                'REFERENCIA': 'referencia', 
                'SOLICITUD': 'solicitud'
            }
        )

        file_fixed = pd.read_excel(
            excel_file, 
            sheet_name='NÓMINA', 
            header=5, 
            usecols='B:M'
        )

        #ORDEN	TIPO DOC	NÚMERO	NOMBRE COTIZANTE	CARGO	AÑO	MES	SALARIO DIAS TRAB	DIAS INCAP	DIAS LICEN	TOTAL DIAS	F.INGRESO

        file_fixed = file_fixed.rename(
            columns={
                'ORDEN': 'orden',
                'TIPO DOC': 'tipo_documento',
                'NÚMERO': 'numero_documento',
                'NOMBRE COTIZANTE': 'nombre_cotizante',
                'CARGO': 'cargo',
                'AÑO': 'anio',
                'MES': 'mes',
                'SALARIO': 'salario',   
                'DIAS TRAB': 'dias_trab',
                'DIAS INCAP': 'dias_incap',
                'DIAS LICEN': 'dias_licen',
                'TOTAL DIAS': 'total_dias',
                'F.INGRESO': 'f_ingreso',

            }
        )


        engine = create_engine('sqlite:///db.sqlite3')

        file_header.to_sql(File_Header._meta.db_table, con=engine, index=False, if_exists='append')
        referencia = pd.read_sql('SELECT "referencia" FROM files_file_header ORDER BY id DESC LIMIT 1', con=engine)
        breakpoint()
        file_fixed['referencia_id'] = referencia['referencia']
        file_fixed.to_sql(File_Fixed._meta.db_table, con=engine, index=False, if_exists='append')

        return render(request, 'file.html')

atlas/users/views.py
from django.shortcuts import render
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, FormView, UpdateView

#Models
from users.models import User
from users.forms import SignUpForm

# Create your views here.

class LoginView(auth_views.LoginView):
    template_name = 'users/login.html'

class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    template_name = 'users/logged_out.html'

class SignUpView(FormView):
    template_name = 'users/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """save form data"""
        form.save()
        return super().form_valid(form)

atlas/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body>

    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>

</body>
</html>

atlas/templates/file.html
{% extends "base.html" %}

{% block head_content %}
    <title>Atlas</title>
{% endblock%}

{% block container %}
    <div style="margin-top: 130px;margin-left: 300px;">
        <form action="{% url "files:feed" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file"
                title="Upload excel file"
                name="excel_file"
                style="border: 1px solid black; padding: 5px;"
                required="required">
            <p>
            <input type="submit"
                value="Upload"
                style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
        </form>
    </div>
{% endblock %}

atlas/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="">
            <img src="{% static "img/atlas.png" %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

atlas/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static "img/atlas.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

atlas/templates/users/login.html
{% extends 'users/base.html' %}

{% block head_content %}
    <title>Atlas</title>
{% endblock  %}

{% block  container %}
    {% if form.errors %}
        <p class="alert alert-danger">
            Your username or password are incorrect
        </p>
    {% endif %}

    <form action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" name="username" placeholder="Username" class="form-control">
        </div>
        <div class="form-group">
            <input type="password" name="password" placeholder="Password" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary btn-block mt-5">Sign in!</button>

        <br>
        <div class="form-group">
            <a href="{% url 'users:signup' %}">Register in here to take the control of your excel</a>
        </div>
    </form>

{% endblock %}

atlas/templates/users/signup.html
{% extends 'users/base.html' %}

{% block head_content %}
    <title>Signup</title>
{% endblock %}

{% block container %}

    <form action={% url 'users:signup' %} method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="btn btn-primary btn-block mt-5">Register!</button>
    </form>
{% endblock container %}